//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSED06_Aquatic_Pet_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECORD_PACKING
    {
        public int RECORD_FK { get; set; }
        public int PACKAGE_FK { get; set; }
        public int QUANTITY { get; set; }
    
        public virtual PET_PACKING PET_PACKING { get; set; }
        public virtual PET_RECORD PET_RECORD { get; set; }
    }
}
