//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSED06_WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DESD06_AQUASHOPEntities : DbContext
    {
        public DESD06_AQUASHOPEntities()
            : base("name=DESD06_AQUASHOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AQUATIC_GROUP> AQUATIC_GROUP { get; set; }
        public virtual DbSet<AQUATIC_PET> AQUATIC_PET { get; set; }
        public virtual DbSet<PET_RECORD> PET_RECORD { get; set; }
        public virtual DbSet<PET_SIZE> PET_SIZE { get; set; }
    }
}
